version: '3.7'

services:
  svn:
    build:
      context: .
    volumes:
    - ./svn-root:/home/svn
    ports:
      - "8080:80"
    restart: "no"
    env_file:
      - .env # Doesn't seem to actually override the default config in Dockerfile
    container_name: wp-metrics-svn-svn