version: '3.7'

services:
  svn:
    build:
      context: .
    volumes:
    - ./svn-root:/home/svn
    ports:
      - "8080:80"
    restart: "no"
    env_file:
      - .env
    container_name: wp-metrics-svn-svn
    stop_grace_period: 30s
    #stop_signal: SIGINT